// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID     string   `json:"id"`
	Post   *Post    `json:"post"`
	Parent *Comment `json:"parent,omitempty"`
	Text   string   `json:"text"`
}

type CommentConnection struct {
	Edges    []*CommentEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type CommentEdge struct {
	Node   *Comment `json:"node"`
	Cursor string   `json:"cursor"`
}

type Mutation struct {
}

type NewComment struct {
	PostID   string  `json:"postId"`
	ParentID *string `json:"parentId,omitempty"`
	Text     string  `json:"text"`
}

type NewPost struct {
	Title         string `json:"title"`
	Text          string `json:"text"`
	AllowComments bool   `json:"allowComments"`
}

type PageInfo struct {
	EndCursor   *string `json:"endCursor,omitempty"`
	HasNextPage bool    `json:"hasNextPage"`
}

type Post struct {
	ID            string             `json:"id"`
	Title         string             `json:"title"`
	Text          string             `json:"text"`
	AllowComments bool               `json:"allowComments"`
	Comments      *CommentConnection `json:"comments"`
}

type Query struct {
}

type Subscription struct {
}
