// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID     string  `json:"id"`
	Post   *Post   `json:"post"`
	Parent *string `json:"parent,omitempty"`
	Text   string  `json:"text"`
}

type Mutation struct {
}

type NewComment struct {
	PostID   string  `json:"postId"`
	ParentID *string `json:"parentId,omitempty"`
	Text     string  `json:"text"`
}

type NewPost struct {
	Title         string `json:"title"`
	Text          string `json:"text"`
	AllowComments bool   `json:"allowComments"`
}

type Post struct {
	ID            string     `json:"id"`
	Title         string     `json:"title"`
	Text          string     `json:"text"`
	AllowComments bool       `json:"allowComments"`
	Comments      []*Comment `json:"comments"`
}

type Query struct {
}
